# backends (4 servers on loopback ports) 
server { listen 127.0.0.1:8081; root /var/www/cloth1; add_header X-Served-By cloth1; }
server { listen 127.0.0.1:8082; root /var/www/cloth2; add_header X-Served-By cloth2; }
server { listen 127.0.0.1:8083; root /var/www/shoes1; add_header X-Served-By shoes1; }
server { listen 127.0.0.1:8084; root /var/www/shoes2; add_header X-Served-By shoes2; }

# load balancer pools 
upstream cloth_pool {
    server 127.0.0.1:8081;
    server 127.0.0.1:8082;
}
upstream shoes_pool {
    server 127.0.0.1:8083;
    server 127.0.0.1:8084;
}

#  main reverse proxy 
server {
    listen 80;
    add_header Cache-Control "no-store" always;

    location / { root /var/www/front; index index.html; }

    location = /cloth { return 301 /cloth/; }
    location = /shoes { return 301 /shoes/; }

    location /cloth/ {
        proxy_pass http://cloth_pool/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /shoes/ {
        proxy_pass http://shoes_pool/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
