Listen 8000
Listen 127.0.0.1:9081
Listen 127.0.0.1:9082
Listen 127.0.0.1:9083
Listen 127.0.0.1:9084

# backend servers 
<VirtualHost 127.0.0.1:9081>
    DocumentRoot /var/www/apache/cloth1
    Header set X-Served-By cloth1
</VirtualHost>
<VirtualHost 127.0.0.1:9082>
    DocumentRoot /var/www/apache/cloth2
    Header set X-Served-By cloth2
</VirtualHost>
<VirtualHost 127.0.0.1:9083>
    DocumentRoot /var/www/apache/shoes1
    Header set X-Served-By shoes1
</VirtualHost>
<VirtualHost 127.0.0.1:9084>
    DocumentRoot /var/www/apache/shoes2
    Header set X-Served-By shoes2
</VirtualHost>

#  reverse pro + load balanc 
<VirtualHost *:8000>
    DocumentRoot /var/www/apache/front
    Header always set Cache-Control "no-store"
    ProxyPreserveHost On

    <Proxy "balancer://clothcluster">
        BalancerMember "http://127.0.0.1:9081"
        BalancerMember "http://127.0.0.1:9082"
        ProxySet lbmethod=byrequests
    </Proxy>

    <Proxy "balancer://shoescluster">
        BalancerMember "http://127.0.0.1:9083"
        BalancerMember "http://127.0.0.1:9084"
        ProxySet lbmethod=byrequests
    </Proxy>

    RedirectMatch ^/cloth$ /cloth/
    RedirectMatch ^/shoes$ /shoes/

    ProxyPass        "/cloth/" "balancer://clothcluster/"
    ProxyPassReverse "/cloth/" "balancer://clothcluster/"
    ProxyPass        "/shoes/" "balancer://shoescluster/"
    ProxyPassReverse "/shoes/" "balancer://shoescluster/"
</VirtualHost>
